const allfile=
[
    {
      "id": 5501,
      "supplier_code": 30319778,
      "supplier_name": "A M B Construction",
      "email_official": "arambera46@gmail.com",
      "website": null,
      "business_telephone": "+265999356276",
      "mobile_number": null,
      "postal_address": "P.O Box 242\nRumphi",
      "business_premise": "Rumphi",
      "expire_date": "10/24/2023",
      "date_s": "10/24/2022",
      "signature": "Irene",
      "branch_name": 111058,
      "account_name": "AMB Trading",
      "account_number": 1630000242281,
      "trading_name": "A B M Construction",
      "company_tin": 95825,
      "number_employees_staff": 4,
      "shareholder_first_name": "Aram",
      "Shareholder_last_name": "Beza",
      "gender": "male",
      "contact_number": null,
      "business_type": "Company",
      "nationality": "Malawian",
      "business_location": "Rumphi",
      "country": "Malawi",
      "supplier_status": "Complete Submission",
      "application_type": "New Application",
      "dg_approval": "Approved",
      "bank_name": "FDH Bank (Commercial Bank)",
      "account_type": "Current",
      "currency": "MWK",
      "msme_type": null,
      "goods_category": "Up to MK30 Million",
      "services_category": "None"
    },
    {
      "id": 4419,
      "supplier_code": 70158764,
      "supplier_name": "A PlusCleaners And General Dealers",
      "email_official": "carolkhu908@gmail.com",
      "website": null,
      "business_telephone": "+265999412741",
      "mobile_number": null,
      "postal_address": "P.O Box 30396\nLilongwe",
      "business_premise": "Area 47/4\nHouse No: 637",
      "expire_date": "8/25/2023",
      "date_s": "8/25/2022",
      "signature": "Edington",
      "branch_name": 50707,
      "account_name": "A Plus Cleaners & General Dealers",
      "account_number": 1008552793,
      "trading_name": "A Plus Cleaners & General Dealers",
      "company_tin": 12060316,
      "number_employees_staff": 15,
      "shareholder_first_name": "Carol",
      "Shareholder_last_name": "Khunga",
      "gender": "female",
      "contact_number": null,
      "business_type": "Company",
      "nationality": "Malawian",
      "business_location": "Lilongwe",
      "country": "Malawi",
      "supplier_status": "Complete Submission",
      "application_type": "Certificate Renewal",
      "dg_approval": "Approved",
      "bank_name": "National Bank of Malawi ",
      "account_type": "Savings",
      "currency": "MWK",
      "msme_type": null,
      "goods_category": "Up to MK10 Million",
      "services_category": "Up to MK200 Million"
    },
    {
      "id": 4044,
      "supplier_code": 70155041,
      "supplier_name": "A S Copy Centre",
      "email_official": "mbazondic@gmail.com",
      "website": null,
      "business_telephone": "+265993630495",
      "mobile_number": null,
      "postal_address": "P.O Box 582\nBlantyre",
      "business_premise": "Kameza \nNear Puma Filling Station",
      "expire_date": "7/28/2023",
      "date_s": "7/28/2022",
      "signature": "Edington",
      "branch_name": 50018,
      "account_name": "A S Copy Centre",
      "account_number": 1008616465,
      "trading_name": "A S Copy Centre",
      "company_tin": 12060557,
      "number_employees_staff": 4,
      "shareholder_first_name": "Alex",
      "Shareholder_last_name": "Singini",
      "gender": "male",
      "contact_number": null,
      "business_type": "Company",
      "nationality": "Malawian",
      "business_location": "Blantyre",
      "country": "Malawi",
      "supplier_status": "Complete Submission",
      "application_type": "Certificate Renewal",
      "dg_approval": "Approved",
      "bank_name": "National Bank of Malawi ",
      "account_type": "Savings",
      "currency": "MWK",
      "msme_type": null,
      "goods_category": "Up to MK80 Million",
      "services_category": "None"
    },
    {
      "id": 8660,
      "supplier_code": 70388759,
      "supplier_name": "A To Z Security Services ",
      "email_official": "atozcompany23@gmail.com",
      "website": null,
      "business_telephone": "+265996746946",
      "mobile_number": "+265996746946",
      "postal_address": "P.O. Box 19 ",
      "business_premise": "Old Town Mzuzu ",
      "expire_date": "6/14/2024",
      "date_s": "6/15/2023",
      "signature": "Edington",
      "branch_name": 110000,
      "account_name": "A To Z Security Services ",
      "account_number": 1620000112331,
      "trading_name": "A To Z Security Services ",
      "company_tin": 70388759,
      "number_employees_staff": 1,
      "shareholder_first_name": "Promise",
      "Shareholder_last_name": "Banda ",
      "gender": "male",
      "contact_number": "+265996746946",
      "business_type": "Company",
      "nationality": "Malawian",
      "business_location": "Mzuzu",
      "country": "Malawi",
      "supplier_status": "Complete Submission",
      "application_type": "New Application",
      "dg_approval": "Approved",
      "bank_name": "FDH Bank (Commercial Bank)",
      "account_type": "Savings",
      "currency": "MWK",
      "msme_type": null,
      "goods_category": "None",
      "services_category": "Up to MK10 Million"
    },
    {
      "id": 8398,
      "supplier_code": 61653498,
      "supplier_name": "A. N. Enterprises",
      "email_official": null,
      "website": null,
      "business_telephone": "+265888692321",
      "mobile_number": "+265888692321",
      "postal_address": "P.O. Box 1483",
      "business_premise": "Livingston Road",
      "expire_date": "5/24/2024",
      "date_s": "5/25/2023",
      "signature": "Edington",
      "branch_name": 110000,
      "account_name": "A. N. Enterprises",
      "account_number": 1040000003935,
      "trading_name": "A. N. Enterprises",
      "company_tin": 176041,
      "number_employees_staff": 1,
      "shareholder_first_name": "Shafi ",
      "Shareholder_last_name": "Asiba",
      "gender": "male",
      "contact_number": "+265888692321",
      "business_type": "Company",
      "nationality": "Malawian",
      "business_location": "Mangochi",
      "country": "Malawi",
      "supplier_status": "Complete Submission",
      "application_type": "New Application",
      "dg_approval": "Approved",
      "bank_name": "FDH Bank (Commercial Bank)",
      "account_type": "Savings",
      "currency": "MWK",
      "msme_type": null,
      "goods_category": "Up to MK30 Million",
      "services_category": "None"
    },
    // {
    //   "id": 8398,
    //   "supplier_code": 61653498,
    //   "supplier_name": "A. N. Enterprises",
    //   "email_official": null,
    //   "website": null,
    //   "business_telephone": "+265888692321",
    //   "mobile_number": "+265888692321",
    //   "postal_address": "P.O. Box 1483",
    //   "business_premise": "Livingston Road",
    //   "expire_date": "5/24/2024",
    //   "date_s": "5/25/2023",
    //   "signature": "Edington",
    //   "branch_name": 110000,
    //   "account_name": "A. N. Enterprises",
    //   "account_number": 1040000003935,
    //   "trading_name": "A. N. Enterprises",
    //   "company_tin": 176041,
    //   "number_employees_staff": 1,
    //   "shareholder_first_name": "Shafi ",
    //   "Shareholder_last_name": "Asiba",
    //   "gender": "male",
    //   "contact_number": "+265888692321",
    //   "business_type": "Company",
    //   "nationality": "Malawian",
    //   "business_location": "Mangochi",
    //   "country": "Malawi",
    //   "supplier_status": "Complete Submission",
    //   "application_type": "New Application",
    //   "dg_approval": "Approved",
    //   "bank_name": "FDH Bank (Commercial Bank)",
    //   "account_type": "Savings",
    //   "currency": "MWK",
    //   "msme_type": null,
    //   "goods_category": "Up to MK30 Million",
    //   "services_category": "None"
    // },
    {
      "id": 3066,
      "supplier_code": 31037543,
      "supplier_name": "A. Nanga Computers",
      "email_official": "jbbnanga@yahoo.com",
      "website": null,
      "business_telephone": "+265999458966",
      "mobile_number": null,
      "postal_address": "P.o. Box 497,\nBlantyre",
      "business_premise": "Livingstone Avenue",
      "expire_date": "5/17/2024",
      "date_s": "5/18/2023",
      "signature": "Edington",
      "branch_name": 50002,
      "account_name": "A. Nanga Computers",
      "account_number": 1000252348,
      "trading_name": "A. Nanga Computers",
      "company_tin": 140976,
      "number_employees_staff": 8,
      "shareholder_first_name": "Ajibu",
      "Shareholder_last_name": "Nanga",
      "gender": "male",
      "contact_number": null,
      "business_type": "Company",
      "nationality": "Malawian",
      "business_location": "Blantyre",
      "country": "Malawi",
      "supplier_status": "Complete Submission",
      "application_type": "Certificate Renewal",
      "dg_approval": "Approved",
      "bank_name": "National Bank of Malawi ",
      "account_type": "Savings",
      "currency": "MWK",
      "msme_type": null,
      "goods_category": "Up to MK500 Million",
      "services_category": "None"
    },
    {
      "id": 7161,
      "supplier_code": 30178801,
      "supplier_name": "A.A.M Furnishers",
      "email_official": "mirzashif@yahoo.com",
      "website": null,
      "business_telephone": "+265999160328",
      "mobile_number": null,
      "postal_address": "P.O Box 960\nLilongwe",
      "business_premise": "Area 4",
      "expire_date": "2/3/2024",
      "date_s": "2/3/2023",
      "signature": "Edington",
      "branch_name": 50608,
      "account_name": "A.A.M Furnitures",
      "account_number": 1849147,
      "trading_name": "A.A.M Furnishers",
      "company_tin": 103048,
      "number_employees_staff": 2,
      "shareholder_first_name": "Asto",
      "Shareholder_last_name": "Mirza",
      "gender": "male",
      "contact_number": null,
      "business_type": "Company",
      "nationality": "Malawian",
      "business_location": "Lilongwe",
      "country": "Malawi",
      "supplier_status": "Complete Submission",
      "application_type": "Certificate Renewal",
      "dg_approval": "Approved",
      "bank_name": "National Bank of Malawi ",
      "account_type": "Current",
      "currency": "MWK",
      "msme_type": null,
      "goods_category": "Up to MK1 Billion",
      "services_category": "None"
    }
  ]



  export { allfile };